### ISSUE TITLE
getting 405 method not allowed

### ISSUE THREAD

**Issue by jampack** [mollie/mollie-api-ruby#134]
mollie-api-ruby (4.6.2)
ruby 2.6.0

method `Mollie::Customer::Subscription.update`

code
```
 def update_subscription
    subscription = Mollie::Customer::Subscription.update(
      subscription_id,
      customer_id: user.customer_id,
      amount: { value: sprintf("%.2f", total), currency: 'EUR' },
    )
  end
```

exception
```
I, [2020-03-12T11:04:26.078066 #1] INFO -- : [9102320438a9af65dec5d19e9694fd6f] Completed 500 Internal Server Error in 126ms (ActiveRecord: 9.0ms)
F, [2020-03-12T11:04:26.078784 #1] FATAL -- : [9102320438a9af65dec5d19e9694fd6f]
F, [2020-03-12T11:04:26.078832 #1] FATAL -- : [9102320438a9af65dec5d19e9694fd6f] Mollie::RequestError (405 Method Not Allowed: Method Not Allowed):
F, [2020-03-12T11:04:26.078864 #1] FATAL -- : [9102320438a9af65dec5d19e9694fd6f]
F, [2020-03-12T11:04:26.078913 #1] FATAL -- : [9102320438a9af65dec5d19e9694fd6f] app/models/order.rb:44:in `update_subscription'
[9102320438a9af65dec5d19e9694fd6f] app/models/order.rb:40:in `recalculate_total_price'
[9102320438a9af65dec5d19e9694fd6f] app/models/good.rb:15:in `checked_out_check'
```

**Comment by justincase** [comment]
Hi,

I believe this error occurs because `subscription_id` is `nil`.
